
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweet_submit_development


test:
  <<: *default
  database: tweet_submit_test


production:
  <<: *default
  database: tweet_submit_production
  username: tweet_submit
  password: <%= ENV['TWEET_SUBMIT_DATABASE_PASSWORD'] %>
